### ISSUE TITLE
Add Document Format Guidelines

### ISSUE THREAD

**Issue by jtriley2p** [virtualjpeg/huff-by-example#3]
# Add Document Format Guidelines

The markdown documents might benefit in terms of readability if we had a formatting guideline. The following are some (incomplete) thoughts on what that might look like. Feedback is welcome!

## General Layout

Page title should be prefixed with `## `.

Sub headers, if any, should be prefixed with `### `.

Explanations should exist above the code blocks.

## Code Formatting

Comments in the example code blocks should either briefly describe a section of the code or contain stack information only.

Example:

```
// MACROS
#define macro THROWOOR = takes (0) returns (0) {
        0x01     // [value]
        0x00     // [offset, value]
        mstore   // []
        0x01     // [length]
        0x00     // [offset, length]
        revert   // []
}
```

Each code should exist on its own line unless the functionality is explicitly explained in the same document.

Example:

"Writing to storage requires the stack to include the value and slot in that order."

```
#define constant OWNER_SLOT = FREE_MEMORY_PTR()

#define macro WRITE = takes(0) returns (0) {
        OWNER_SLOT caller sstore
}
```

**Comment by virtualjpeg** [comment]
sounds good to me.

**Comment by virtualjpeg** [comment]
let’s write a full list.
